### PR TITLE
SpinKube on Gardener Shoot cluster blog post

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**What this PR does / why we need it**:
A blog post that shows how Gardener can integrate with [SpinKube](https://www.spinkube.dev/).
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
@n-boshnakov Can you please proofread this?

**Release note**:

```improvement operator

```

### CODE REVIEW

**Review by n-boshnakov — CHANGES_REQUESTED** [review]
The blog looks really good, I only have some minor punctuation suggestions.

**Comment by dimityrmirchev** [comment]
Thanks @n-boshnakov! It should look better now, PTAL

**Review by n-boshnakov — DISMISSED** [review]
/lgtm

**Review by JordanJordanov — APPROVED** [review]
/lgtm

**Pull request merged**
