### PR TITLE
Hardened Shoots Report

### PR DESCRIPTION
**Pull request by gardener-robot-ci-1**
This PR contains DISA K8s STIGs compliance evidence. This includes the latest diki report against hardened shoot clusters, their shoot configurations and the diki configuration used for the run.

### CODE REVIEW

**Comment by AleksandarSavchev** [comment]
/hold

Required some changes to `website.yaml` and the `build` script in `website-generator`

**Review by JordanJordanov — COMMENTED** [review]
/lgtm

**Review by JordanJordanov — APPROVED** [review]

**Review by n-boshnakov — DISMISSED** [review]
/lgtm

**Review by n-boshnakov — APPROVED** [review]
/lgtm

**Review by Kostov6 — APPROVED** [review]
/lgtm

**Pull request merged**
