### PR TITLE
Add cert-management tutorials for Gardener.

### PR DESCRIPTION
**Pull request by timuthy**
This PR adds an operator as well as an app-developer tutorial for certificate management via Gardener.

### CODE REVIEW

**Comment by timuthy** [comment]
Thanks @rfranzke, PTAL.

**Comment by freegroup** [comment]
"example/10-secret-certificate-management-config.yaml" is't a link....I will change this

**Comment by freegroup** [comment]
where is the file "/dev/20-componentconfig-gardener-controller-manager.yaml" located?

**Comment by freegroup** [comment]
https://github.com/gardener/gardener/blob/master/example/20-componentconfig-gardener-controller-manager.yaml or?

**Comment by timuthy** [comment]
Thanks @freegroup.

**Pull request merged**
