### PR TITLE
add documentation and ops guide to guidelines

### PR DESCRIPTION
**Pull request by RaphaelVogel**

### CODE REVIEW

**Comment by g-pavlov** [comment]
Are there further changes pending here or we can merge.

**Comment by g-pavlov** [comment]
This has been open for far quite long without progress. Please, move on with it or close it.

**Comment by RaphaelVogel** [comment]
can be merged, should I

**Comment by RaphaelVogel** [comment]
CLA assistant seems not to work. See an empty page

**Comment by g-pavlov** [comment]
> CLA assistant seems not to work. See an empty page

@msohn

**Pull request merged**
