### PR TITLE
Remove duplicate "Authenticating with an Identity Provider"

### PR DESCRIPTION
**Pull request by JensHaley**
**What this PR does / why we need it**:

There are currently two tutorials "Authenticating with an Identity Provider" on github.com:

* [Authenticating with an Identity Provider (last update: Dec 11, 2020)](https://github.com/gardener/documentation/blob/master/website/documentation/tutorials/oidc-login/_index.md)
* [Authenticating with an Identity Provider (last update: Nov 19, 2020)](https://github.com/gardener/documentation/blob/master/website/documentation/guides/client_tools/oidc-login/_index.md)

I would like to remove the outdated one to avoid double maintenance.

### CODE REVIEW

**Comment by g-pavlov** [comment]
from @mvladev: This one is normative: https://github.com/gardener/documentation/blob/master/website/documentation/guides/client_tools/working-with-kubeconfig/_index.md
Certificates should not be used to authenticate humans

**Review by g-pavlov — CHANGES_REQUESTED** [review]
use https://github.com/gardener/documentation/blob/master/website/documentation/guides/client_tools/working-with-kubeconfig/_index.md as per the feedback from @mvladev

**Comment by JensHaley** [comment]
@g-pavlov : I am sorry, but you mixed something up. :-)

@mvladev 's feedback was about two versions of **working-with-kubeconfig** (one here on github.com, and one on github.tools):
https://github.com/gardener/documentation/blob/master/website/documentation/guides/client_tools/working-with-kubeconfig/_index.md

This PR is related to two versions on github.com of **oidc-login**:
https://github.com/gardener/documentation/blob/master/website/documentation/tutorials/oidc-login/_index.md
https://github.com/gardener/documentation/blob/master/website/documentation/guides/client_tools/oidc-login/_index.md

The first one in folder `/tutorials` was updated by me and approved in this PR: https://github.com/gardener/documentation/pull/183
Soo the one in folder `/client_tools` should be obsolete.

**Review by swilen-iwanow — APPROVED** [review]
/lgtm

**Pull request merged**
