### PR TITLE
adopter: Add B1 Systems GmbH

### PR DESCRIPTION
**Pull request by NotTheEvilOne**
**What this PR does / why we need it**:
This PR adds a section about B1 Systems GmbH as an adopter.

### CODE REVIEW

**Comment by NotTheEvilOne** [comment]
I hope the image size works out well for the layout. If you see any issues please don't hesitate to contact me.

**Comment by NotTheEvilOne** [comment]
I would like to revive this PR. Could you kindly let me know if anything is missing to merge this?

**Comment by swilen-iwanow** [comment]
Hi, the image is shown slightly smaller than the others on the page, if this is not a problem for you we can continue with the merge. Do you have an image where the Logo and title are on different rows. If not we can proceed with the merge

**Comment by NotTheEvilOne** [comment]
I'll try to clarify this and get back to you :) Thanks so far.

**Comment by NotTheEvilOne** [comment]
Hi @swilen-iwanow. Sorry for getting back to you late. We have finally clarified an image variant that renders well for FHD. We would highly appreciate your support in getting the PR merged :)

**Review by Kristian-ZH — APPROVED** [review]
Thanks for the PR

/lgtm

**Pull request merged**
