### PR TITLE
Removed excess contributions page

### PR DESCRIPTION
**Pull request by n-boshnakov**
Combined the content of both Contributions pages, removing the excess one. Also replaced all links pointing to the deleted page with links to the current one.

**What this PR does / why we need it**:
This PR removes an unneeded copy of the contributions page, while keeping the changes made to it. It also replaces all links pointing to the deleted page.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Release note**:

```improvement developer
NONE
```

### CODE REVIEW

**Comment by JordanJordanov** [comment]
Please, don't forget to incorporate the changes from https://github.com/gardener/documentation/pull/276. It seems like you have decided to delete the file which Matthias has changed

**Comment by n-boshnakov** [comment]
> Please, don't forget to incorporate the changes from #276. It seems like you have decided to delete the file which Matthias has changed

My mistake, I thought that the changes were already merged with the master branch and copied the contents of his file. I have fixed the issue. 

I decided to keep the _index.md file instead of the CONTRIBUTIONS.md, since I felt it was more incorporated into the structure of the website. Regardless of that, if you think that we should keep the CONTRIBUTIONS.md file, I will instead remove the _index.md. Regardless of which file is kept, the content in it will include all the changes Matthias has made.

**Comment by JordanJordanov** [comment]
> I decided to keep the _index.md file 
That's OK for the time being
With the introduction of the components on the site we may want to move this file in gardener/gardener (https://github.com/gardener/gardener/blob/master/CONTRIBUTING.md) allowing every component to ptovide its own contributing guide.

**Review by JordanJordanov — APPROVED** [review]

**Pull request merged**
