### PR TITLE
Fixed broken links - 2023.06

### PR DESCRIPTION
**Pull request by n-boshnakov**
**What this PR does / why we need it**:
Fixed broken links in the documentation.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement developer
NONE
```

### CODE REVIEW

**Review by JordanJordanov — APPROVED** [review]
/lgtm

**Review by JordanJordanov — APPROVED** [review]
/lgtm

**Comment by JordanJordanov** [comment]
@Kostov6 is this check correct? The reported external link seems to be correct.

> Error: 1 error occurred:
	* parse "(https://etcd.io/docs/v2/admin_guide/": first path segment in URL cannot contain colon

**Comment by n-boshnakov** [comment]
> @Kostov6 is this check correct? The reported external link seems to be correct.
> 
> > Error: 1 error occurred:
> > * parse "(https://etcd.io/docs/v2/admin_guide/": first path segment in URL cannot contain colon

We have already fixed that error in the repo it originates from, I think a retest of the PR is needed.

**Pull request merged**
