### PR TITLE
remove security policy

### PR DESCRIPTION
**Pull request by RaphaelVogel**
The security policy is now centrally maintained (https://github.com/gardener/.github/blob/main/SECURITY.MD) and all gardener repos automatically inherit this policy if they have not defined their own

### CODE REVIEW

**Review by n-boshnakov — APPROVED** [review]
/lgtm

**Comment by n-boshnakov** [comment]
Looks good to me, I also assigned Jordan Jordanov as a reviewer for a second opinion.

**Comment by JordanJordanov** [comment]
@n-boshnakov We shall make sure that the current page (https://gardener.cloud/docs/contribute/code/security-guide/) is shown somewhere else in the site. Or even better,  can we keep the page (and the url) but point it to https://github.com/gardener/.github/blob/main/SECURITY.MD ?

**Comment by n-boshnakov** [comment]
> @n-boshnakov We shall make sure that the current page (https://gardener.cloud/docs/contribute/code/security-guide/) is shown somewhere else in the site. Or even better, can we keep the page (and the url) but point it to https://github.com/gardener/.github/blob/main/SECURITY.MD ?

Yes, we can do something like that. I'll test it out and if it works, I'll close the PR and open a new one with the changes, as I will be modifying the file that this PR deletes.

**Comment by n-boshnakov** [comment]
Closing this PR, as the changes are applied in #466

**Pull request closed without merging**
