### PR TITLE
ccwienk added to the Gardener Security Team

### PR DESCRIPTION
**Pull request by ThormaehlenFred**

### CODE REVIEW

**Comment by ThormaehlenFred** [comment]
Hi @ccwienk please merge this PR

**Comment by freegroup** [comment]
@ThormaehlenFred there is a conflict in the security-release-process. Can you please have a look which one is the good one?

**Comment by vpnachev** [comment]
Conflicts are resolved.

**Comment by vpnachev** [comment]
Closing in favor of https://github.com/gardener/documentation/commit/5e613e90b5ff896f28e6a4202a83b6e76e01669d

**Pull request closed without merging**
