### PR TITLE
Use "Architecture" file from gardener/gardener repository

### LINKED ISSUE #231: Move Architecture.md from Github wiki to documentation git repository
**What would you like to be added**:
concepts/architecture is currently sourced from Github wiki https://github.com/gardener/documentation/wiki/Architecture.md but would be better maintained directly inside gardener/documentation.git (or even gardener/gardener.git?)

**Why is this needed**:
The Wiki is not open to outside collaborators and does not support workflows like Pull requests. The License of the wiki content is unclear to me. This is the only documentation page that is maintained in a Github wiki.

### PR DESCRIPTION
**Pull request by berendt**
Closes #231

Signed-off-by: Christian Berendt <berendt@23technologies.cloud>

### CODE REVIEW

**Comment by berendt** [comment]
Depends on https://github.com/gardener/gardener/pull/3923.

**Comment by berendt** [comment]
@rfranzke Can you please have a look on this one?

**Review by rfranzke — APPROVED** [review]
/lgtm

Thanks!

**Pull request merged**
